import { useState } from "react";

type Period = "24H" | "7D" | "30D";

const reportData = {
  "24H": {
    label: "LAST 24 HOURS",
    threats: "1,284",
    threatsChange: "+12.4%",
    critical: "07",
    contained: "143",
    containedChange: "+18.7%",
    risk: "ELEVATED",
    review: "3 EVENTS REQUIRE REVIEW",
    distribution: [
      ["PHISHING", 38],
      ["BEHAVIOURAL", 27],
      ["IMPERSONATION", 19],
      ["DEEPFAKE", 16],
    ],
    risks: [
      ["07", "CRITICAL"],
      ["24", "HIGH"],
      ["81", "MEDIUM"],
      ["142", "LOW"],
    ],
    incidents: [
      ["INC-2841", "Credential Theft", "RESOLVED", "2m ago"],
      ["INC-2839", "Malware Execution", "INVESTIGATING", "8m ago"],
      ["INC-2837", "Phishing Attempt", "CONTAINED", "14m ago"],
      ["INC-2832", "Suspicious Login", "MONITORING", "31m ago"],
    ],
  },

  "7D": {
    label: "LAST 7 DAYS",
    threats: "8,742",
    threatsChange: "+21.8%",
    critical: "31",
    contained: "896",
    containedChange: "+24.3%",
    risk: "HIGH",
    review: "8 EVENTS REQUIRE REVIEW",
    distribution: [
      ["PHISHING", 34],
      ["BEHAVIOURAL", 29],
      ["IMPERSONATION", 21],
      ["DEEPFAKE", 16],
    ],
    risks: [
      ["31", "CRITICAL"],
      ["96", "HIGH"],
      ["418", "MEDIUM"],
      ["1,204", "LOW"],
    ],
    incidents: [
      ["INC-2841", "Credential Theft", "RESOLVED", "2h ago"],
      ["INC-2839", "Malware Execution", "INVESTIGATING", "5h ago"],
      ["INC-2837", "Phishing Campaign", "CONTAINED", "1d ago"],
      ["INC-2828", "Account Takeover", "RESOLVED", "2d ago"],
    ],
  },

  "30D": {
    label: "LAST 30 DAYS",
    threats: "36,418",
    threatsChange: "+28.6%",
    critical: "118",
    contained: "3,742",
    containedChange: "+31.5%",
    risk: "MODERATE",
    review: "12 EVENTS REQUIRE REVIEW",
    distribution: [
      ["PHISHING", 31],
      ["BEHAVIOURAL", 30],
      ["IMPERSONATION", 23],
      ["DEEPFAKE", 16],
    ],
    risks: [
      ["118", "CRITICAL"],
      ["384", "HIGH"],
      ["1,842", "MEDIUM"],
      ["5,917", "LOW"],
    ],
    incidents: [
      ["INC-2841", "Credential Theft", "RESOLVED", "2d ago"],
      ["INC-2819", "Deepfake Attempt", "CONTAINED", "6d ago"],
      ["INC-2798", "Phishing Campaign", "RESOLVED", "11d ago"],
      ["INC-2764", "Suspicious Login", "MONITORING", "18d ago"],
    ],
  },
} satisfies Record<Period, {
  label: string;
  threats: string;
  threatsChange: string;
  critical: string;
  contained: string;
  containedChange: string;
  risk: string;
  review: string;
  distribution: [string, number][];
  risks: [string, string][];
  incidents: [string, string, string, string][];
}>;

export default function Reports() {
  const [period, setPeriod] = useState<Period>("24H");
  const [generated, setGenerated] = useState(false);
  const [exported, setExported] = useState(false);

  const data = reportData[period];

  const generateReport = () => {
    setGenerated(false);
    window.setTimeout(() => setGenerated(true), 900);
  };

  const exportReport = () => {
    const textReport = `
CYBERGUARD SECURITY REPORT
==========================

REPORTING PERIOD: ${data.label}

SECURITY POSTURE
----------------
Threats Detected: ${data.threats}
Threat Change: ${data.threatsChange}
Critical Events: ${data.critical}
Incidents Contained: ${data.contained}
Containment Change: ${data.containedChange}
Overall Risk: ${data.risk}

THREAT DISTRIBUTION
-------------------
${data.distribution.map(([name, value]) => `${name}: ${value}%`).join("\n")}

RISK DISTRIBUTION
-----------------
${data.risks.map(([value, name]) => `${name}: ${value}`).join("\n")}

RECENT INCIDENTS
----------------
${data.incidents.map(
  ([id, title, status, time]) => `${id} | ${title} | ${status} | ${time}`
).join("\n")}

Generated by CyberGuard Security Intelligence.
`;

    const blob = new Blob([textReport], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");

    a.href = url;
    a.download = `CYBERGUARD-${period}-Security-Report.txt`;
    a.click();

    URL.revokeObjectURL(url);

    setExported(true);
    window.setTimeout(() => setExported(false), 1800);
  };

  return (
    <div className="reports-page">
      <div className="reports-hero">
        <div>
          <div className="reports-eyebrow">
            SECURITY REPORTING / LIVE
          </div>

          <h1>SECURITY REPORTS</h1>

          <p>
            Review security activity, threat trends and incident outcomes
            across the CyberGuard security environment.
          </p>
        </div>

        <div className="reports-engine">
          <span className="status-dot" />
          REPORTING ENGINE ONLINE
        </div>
      </div>

      <div className="report-toolbar">
        <div>
          <span className="report-period-label">REPORT PERIOD</span>

          <div className="report-periods">
            {(["24H", "7D", "30D"] as Period[]).map((item) => (
              <button
                key={item}
                className={period === item ? "active" : ""}
                onClick={() => {
                  setPeriod(item);
                  setGenerated(false);
                  setExported(false);
                }}
              >
                {item}
              </button>
            ))}
          </div>
        </div>

        <div className="report-actions">
          <button onClick={generateReport}>
            {generated ? "REPORT GENERATED" : "GENERATE REPORT"}
          </button>

          <button onClick={exportReport}>
            {exported ? "REPORT EXPORTED" : "EXPORT REPORT"}
          </button>
        </div>
      </div>

      <section className="soc-panel report-summary-panel">
        <div className="panel-header">
          <div>
            <span>EXECUTIVE SECURITY SUMMARY</span>
            <h2>SECURITY POSTURE</h2>
          </div>

          <strong>{data.label}</strong>
        </div>

        <div className="report-metrics">
          <div>
            <span>THREATS DETECTED</span>
            <strong>{data.threats}</strong>
            <small>{data.threatsChange}</small>
          </div>

          <div>
            <span>CRITICAL EVENTS</span>
            <strong>{data.critical}</strong>
            <small className="critical-text">HIGH PRIORITY</small>
          </div>

          <div>
            <span>INCIDENTS CONTAINED</span>
            <strong>{data.contained}</strong>
            <small>{data.containedChange}</small>
          </div>

          <div>
            <span>OVERALL RISK</span>
            <strong className="risk-value">{data.risk}</strong>
            <small>{data.review}</small>
          </div>
        </div>
      </section>

      <div className="reports-grid">
        <section className="soc-panel">
          <div className="panel-header">
            <div>
              <span>THREAT DISTRIBUTION</span>
              <h2>DETECTION CATEGORIES</h2>
            </div>
          </div>

          <div className="distribution-list">
            {data.distribution.map(([name, value]) => (
              <div className="distribution-row" key={name}>
                <div>
                  <span>{name}</span>
                  <strong>{value}%</strong>
                </div>

                <div className="distribution-bar">
                  <div style={{ width: `${value}%` }} />
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="soc-panel">
          <div className="panel-header">
            <div>
              <span>RISK DISTRIBUTION</span>
              <h2>THREAT SEVERITY</h2>
            </div>
          </div>

          <div className="risk-distribution">
            {data.risks.map(([value, name]) => (
              <div className="risk-card" key={name}>
                <strong>{value}</strong>
                <span>{name}</span>
              </div>
            ))}
          </div>
        </section>
      </div>

      <section className="soc-panel report-incidents-panel">
        <div className="panel-header">
          <div>
            <span>INCIDENT ACTIVITY</span>
            <h2>RECENT INCIDENTS</h2>
          </div>
        </div>

        <div className="report-incident-list">
          {data.incidents.map(([id, title, status, time]) => (
            <div className="report-incident" key={id}>
              <div>
                <strong>{id}</strong>
                <span>{title}</span>
              </div>

              <div>
                <b className={`incident-status ${status.toLowerCase()}`}>
                  {status}
                </b>
                <small>{time}</small>
              </div>
            </div>
          ))}
        </div>
      </section>

      {generated && (
        <div className="report-success">
          SECURITY REPORT GENERATED — {data.label} ANALYSIS COMPLETE
        </div>
      )}
    </div>
  );
}
